add_bos_token: true
do_sample: false
dynatemp_base: 1
early_stopping: false
epsilon_cutoff: 0
eta_cutoff: 0
grammar: ''
guidance_scale: 0.01
length_penalty: 0
max_context_length: 32769
max_tokens: 752
min_length: 37
min_p: 0
mirostat: 0
mirostat_eta: 0
mirostat_tau: 4.99
negative_prompt: ''
no_repeat_ngram_size: 0
num_beams: 2
penalty_alpha: 0
repetition_penalty: 1.08
repetition_penalty_range: 14
seed: -1
skip_special_tokens: false
smoothing_factor: 0
stream: true
temperature: 0.8
tfs: 1
top_a: 0.04
top_k: 43
top_p: 0.9
typical_p: 1
use_default_badwordids: false
